name: Feature Request
description: Suggest an idea for twilio-node
title: "[Feature Request]: "
labels: "type: community enhancement"
body:
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/twilio/twilio-node/blob/main/CONTRIBUTING.md) for this project.
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/twilio/twilio-node/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](https://github.com/twilio/twilio-node/issues) for a feature request that matches the one I want to file, without success.
          required: true
        - label: This is not a general Twilio feature request or bug report. It is a feature request for the twilio-node JavaScript package.
          required: true
  - type: textarea
    attributes:
      label: Problem Description
      description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the solution you would like in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Add any other context about the problem here.
    validations:
      required: false