/**
 * This code was generated by
 * \ / _    _  _|   _  _
 *  | (_)\/(_)(_|\/| |(/_  v1.0.0
 *       /       /
 */

import Page = require('../../../../../base/Page');
import Response = require('../../../../../http/response');
import Understand = require('../../../Understand');
import { SerializableClass } from '../../../../../interfaces';

/**
 * @description Initialize the SampleList
 * PLEASE NOTE that this class contains preview products that are subject to change. Use them with caution. If you currently do not have developer preview access, please contact help@twilio.com.
 *
 * @param version - Version of the resource
 * @param assistantSid - The unique ID of the Assistant.
 * @param intentSid - The unique ID of the Intent associated with this Sample.
 */
declare function SampleList(version: Understand, assistantSid: string, intentSid: string): SampleListInstance;

interface SampleResource {
  account_sid: string;
  assistant_sid: string;
  date_created: Date;
  date_updated: Date;
  intent_sid: string;
  language: string;
  sid: string;
  source_channel: string;
  tagged_text: string;
  url: string;
}

interface SamplePayload extends SampleResource, Page.TwilioResponsePayload {
}

interface SampleSolution {
  assistantSid?: string;
  intentSid?: string;
}

interface SampleListInstance {
  /**
   * @param sid - sid of instance
   */
  (sid: string): SampleContext;
  /**
   * create a SampleInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  create(opts: SampleListInstanceCreateOptions, callback?: (error: Error | null, items: SampleListInstance) => any): Promise<SampleInstance>;
  /**
   * Streams SampleInstance records from the API.
   *
   * This operation lazily loads records as efficiently as possible until the limit
   * is reached.
   *
   * The results are passed into the callback function, so this operation is memory efficient.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Function to process each record
   */
  each(opts?: SampleListInstanceEachOptions, callback?: (item: SampleInstance, done: (err?: Error) => void) => void): void;
  /**
   * Constructs a sample
   *
   * @param sid - The sid
   */
  get(sid: string): SampleContext;
  /**
   * Retrieve a single target page of SampleInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param targetUrl - API-generated URL for the requested results page
   * @param callback - Callback to handle list of records
   */
  getPage(targetUrl?: string, callback?: function): Promise<SamplePage>;
  /**
   * @description Lists SampleInstance records from the API as a list.
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle list of records
   */
  list(opts?: SampleListInstanceOptions, callback?: function): Promise<SampleInstance[]>;
  /**
   * Retrieve a single page of SampleInstance records from the API.
   * Request is executed immediately
   *
   * If a function is passed as the first argument, it will be used as the callback function.
   *
   * @param opts - Options for request
   * @param callback - Callback to handle list of records
   */
  page(opts?: SampleListInstancePageOptions, callback?: function): Promise<SamplePage>;
}

/**
 * Options to pass to update
 *
 * @property language - An ISO language-country string of the sample.
 * @property taggedText - The text example of how end-users may express this intent. The sample may contain Field tag blocks.
 * @property sourceChannel - The communication channel the sample was captured. It can be: voice, sms, chat, alexa, google-assistant, or slack. If not included the value will be null
 */
export interface SampleInstanceUpdateOptions {
  language?: string;
  sourceChannel?: string;
  taggedText?: string;
}

/**
 * Options to pass to update
 *
 * @property language - An ISO language-country string of the sample.
 * @property taggedText - The text example of how end-users may express this intent. The sample may contain Field tag blocks.
 * @property sourceChannel - The communication channel the sample was captured. It can be: voice, sms, chat, alexa, google-assistant, or slack. If not included the value will be null
 */
export interface SampleContextUpdateOptions {
  language?: string;
  sourceChannel?: string;
  taggedText?: string;
}

/**
 * Options to pass to each
 *
 * @property language - An ISO language-country string of the sample.
 * @property limit -
 *                         Upper limit for the number of records to return.
 *                         each() guarantees never to return more than limit.
 *                         Default is no limit
 * @property pageSize -
 *                         Number of records to fetch per request,
 *                         when not set will use the default value of 50 records.
 *                         If no pageSize is defined but a limit is defined,
 *                         each() will attempt to read the limit with the most efficient
 *                         page size, i.e. min(limit, 1000)
 * @property callback -
 *                         Function to process each record. If this and a positional
 *                         callback are passed, this one will be used
 * @property done - Function to be called upon completion of streaming
 */
export interface SampleListInstanceEachOptions {
  callback?: (item: SampleInstance, done: (err?: Error) => void) => void;
  done?: Function;
  language?: string;
  limit?: number;
  pageSize?: number;
}

/**
 * Options to pass to list
 *
 * @property language - An ISO language-country string of the sample.
 * @property limit -
 *                         Upper limit for the number of records to return.
 *                         list() guarantees never to return more than limit.
 *                         Default is no limit
 * @property pageSize -
 *                         Number of records to fetch per request,
 *                         when not set will use the default value of 50 records.
 *                         If no page_size is defined but a limit is defined,
 *                         list() will attempt to read the limit with the most
 *                         efficient page size, i.e. min(limit, 1000)
 */
export interface SampleListInstanceOptions {
  language?: string;
  limit?: number;
  pageSize?: number;
}

/**
 * Options to pass to page
 *
 * @property language - An ISO language-country string of the sample.
 * @property pageToken - PageToken provided by the API
 * @property pageNumber - Page Number, this value is simply for client state
 * @property pageSize - Number of records to return, defaults to 50
 */
export interface SampleListInstancePageOptions {
  language?: string;
  pageNumber?: number;
  pageSize?: number;
  pageToken?: string;
}

/**
 * Options to pass to create
 *
 * @property language - An ISO language-country string of the sample.
 * @property taggedText - The text example of how end-users may express this intent. The sample may contain Field tag blocks.
 * @property sourceChannel - The communication channel the sample was captured. It can be: voice, sms, chat, alexa, google-assistant, or slack. If not included the value will be null
 */
export interface SampleListInstanceCreateOptions {
  language: string;
  sourceChannel?: string;
  taggedText: string;
}


declare class SamplePage extends Page {
  /**
   * @constructor Twilio.Preview.Understand.AssistantContext.IntentContext.SamplePage
   * @augments Page
   * @description Initialize the SamplePage
   * PLEASE NOTE that this class contains preview products that are subject to change. Use them with caution. If you currently do not have developer preview access, please contact help@twilio.com.
   *
   * @param version - Version of the resource
   * @param response - Response from the API
   * @param solution - Path solution
   */
  constructor(version: Twilio.Preview.Understand, response: Response<string>, solution: object);

  /**
   * Build an instance of SampleInstance
   *
   * @param payload - Payload response from the API
   */
  getInstance(payload: object);
}


declare class SampleInstance {
  /**
   * @constructor Twilio.Preview.Understand.AssistantContext.IntentContext.SampleInstance
   * @description Initialize the SampleContext
   * PLEASE NOTE that this class contains preview products that are subject to change. Use them with caution. If you currently do not have developer preview access, please contact help@twilio.com.
   *
   * @property accountSid - The unique ID of the Account that created this Sample.
   * @property dateCreated - The date that this resource was created
   * @property dateUpdated - The date that this resource was last updated
   * @property intentSid - The unique ID of the Intent associated with this Sample.
   * @property language - An ISO language-country string of the sample.
   * @property assistantSid - The unique ID of the Assistant.
   * @property sid - A 34 character string that uniquely identifies this resource.
   * @property taggedText - The text example of how end-users may express this intent. The sample may contain Field tag blocks.
   * @property url - The url
   * @property sourceChannel - The communication channel the sample was captured. It can be: voice, sms, chat, alexa, google-assistant, or slack. If not included the value will be null
   *
   * @param version - Version of the resource
   * @param payload - The instance payload
   * @param assistantSid - The unique ID of the Assistant.
   * @param intentSid - The unique ID of the Intent associated with this Sample.
   * @param sid - The sid
   */
  constructor(version: Twilio.Preview.Understand, payload: object, assistantSid: sid, intentSid: sid, sid: sid);

  _proxy?: SampleContext;
  /**
   * fetch a SampleInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback?: (error: Error | null, items: SampleInstance) => any);
  /**
   * remove a SampleInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback?: (error: Error | null, items: SampleInstance) => any);
  /**
   * Produce a plain JSON object version of the SampleInstance for serialization.
   * Removes any circular references in the object.
   */
  toJSON();
  /**
   * update a SampleInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  update(opts?: SampleInstanceUpdateOptions, callback?: (error: Error | null, items: SampleInstance) => any);
}


declare class SampleContext {
  /**
   * @constructor Twilio.Preview.Understand.AssistantContext.IntentContext.SampleContext
   * @description Initialize the SampleContext
   * PLEASE NOTE that this class contains preview products that are subject to change. Use them with caution. If you currently do not have developer preview access, please contact help@twilio.com.
   *
   * @param version - Version of the resource
   * @param assistantSid - The assistant_sid
   * @param intentSid - The intent_sid
   * @param sid - The sid
   */
  constructor(version: Twilio.Preview.Understand, assistantSid: sid_like, intentSid: sid_like, sid: sid);

  /**
   * fetch a SampleInstance
   *
   * @param callback - Callback to handle processed record
   */
  fetch(callback?: (error: Error | null, items: SampleContext) => any);
  /**
   * remove a SampleInstance
   *
   * @param callback - Callback to handle processed record
   */
  remove(callback?: (error: Error | null, items: SampleContext) => any);
  /**
   * update a SampleInstance
   *
   * @param opts - Options for request
   * @param callback - Callback to handle processed record
   */
  update(opts?: SampleContextUpdateOptions, callback?: (error: Error | null, items: SampleContext) => any);
}

export { SampleContext, SampleInstance, SampleList, SampleListInstance, SamplePage, SamplePayload, SampleResource, SampleSolution }
